server:
  port: 8510

spring:
  application:
    name: task-service-dev  # 개발 환경에 맞는 애플리케이션 이름

  messages:
    basename: messages/messages
    encoding: UTF-8
    use-code-as-default-message: false
    fallback-to-system-locale: false
    cache-duration: 3600
    always-use-message-format: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8310/eureka
  instance:
    prefer-ip-address: true

