spring:
  application:
    name: front-service

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8100
#  port: 8101

onebook:
  gatewayUrl: http://localhost:8200

nhnKey:
  url: https://api-keymanager.nhncloudservice.com
  appKey: qTQNj7LyHhdAazH3
  keyPath: 1nebook.p12
  password: 1nebook
  keyId: a53e608fbf3744a594162277fb824907
  default_db: 201
  cart_redis_db: 202