spring:
  application:
    name: eureka
  lifecycle:
    timeout-per-shutdown-phase: 10s
  security:
    user:
      name: admin
      password: 1234
  profiles:
    active: peer1

#server:
#  shutdown: graceful

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  # eviction-interval-timer-in-ms: 5000
  # response-cache-update-interval-ms: 5000
